### ISSUE TITLE
Please tag release

### ISSUE THREAD

**Issue by tillea** [ucscGenomeBrowser/kent-core#1]
**Describe the bug**
This repository does not contain a tag

 **Expected behavior**
I'd like to create a Debian package of this code.  It helps a lot to spot new versions that are targeting end users if you would tag the according commit with a version.

Thanks a lot for publishing this code as free software, Andreas.

**Comment by maximilianh** [comment]
Good point. Done now and added to makeKentCore script.

**Comment by maximilianh** [comment]
I could also make "releases", which is a github feature, I think it makes a stable zip of the entire repo, but I doubt that you really need that.

**Comment by tillea** [comment]
Am Fri, Mar 31, 2023 at 01:19:43AM -0700 schrieb Maximilian Haeussler:
> I could also make "releases", which is a github feature, I think it makes a stable zip of the entire repo, but I doubt that you really need that.

Making releases seems a consequent thing to do.  Since the release URL changed over time at least twice we rather trust tags that remained stable.  We do not need that zip feature for Debian but others might like it.
Thanks a lot for the quick response, Andreas.
