### ISSUE TITLE
Makefile contains targets which can only be built in full source tree

### ISSUE THREAD

**Issue by tillea** [ucscGenomeBrowser/kent-core#2]
**Describe the bug**
I tried to build the source tree as is to create a Debian package but failed due to several references to code parts that are not contained in kent-core.  I've written a [patch](https://salsa.debian.org/med-team/kent-core/-/blob/master/debian/patches/fix_makefile.patch) to fix several issues but its not complete yet.

 **To Reproduce**
 1. Try `make clean` to get a first impression what's going on.
 2. Try `make` to see what's happening.

 **Expected behavior**
Building should be possible without parts of `ucscGenomeBrowser/kent` that are not (yet) part of kent-core.  The [patch](https://salsa.debian.org/med-team/kent-core/-/blob/master/debian/patches/fix_makefile.patch) I've created should perfectly work inside the full source tree since its always checking whether a directory exists or not (sometimes with `make wildcard` sometimes with `shell if` - no idea what you might prefer in the long run thus filling this issue to discuss about next steps.

I stopped [here](https://salsa.debian.org/med-team/kent-core/-/jobs/4107560) when I was running into:

    make[2]: *** No rule to make target '../lib/x86_64/jkOwnLib.a', needed by 'webBlat'.  Stop.
    make[2]: Leaving directory '/builds/med-team/kent-core/debian/output/source_dir/src/webBlat'

since I'm wondering whether you might like to consider providing `jkOwnLib.a` source code with MIT license to be able to build `webBlat` which is not possible yet.

 **Desktop (please complete the following information):**
  - OS: Debian

Kind regards, Andreas.

**Comment by maximilianh** [comment]
Sorry for the long delay, the problem was that I accidentally had removed the top-level "makefile" which was supposed to solve this. I've added it back now. This new, additional top-level makefile (which doesn't exist in the full kent source tree) runs only "make utils" so non-functional BLAT targets should not be an issue now. I think that's a smaller change than what your patch suggests.

Let me know if you run into another problem, I will get back to you quicker next time.

**Comment by tillea** [comment]
Well, I confirm that the build goes more smoothly now - but its not true that its just because of the missing `makefile`.  The clean target remains broken if you test

    cd src && make clean

it ends up with

    cd lib && make clean
    /bin/sh: 1: cd: can't cd to lib

I did not changed the tarball (yet) since it has no tagged release and I can override the build process in `debian/rules` [easily](https://salsa.debian.org/med-team/kent-core/-/blob/master/debian/rules#L14-L15).  However, even in this case the build process [fails](https://salsa.debian.org/med-team/kent-core/-/jobs/4130819) with

    cd blat && make test
    /bin/sh: 1: cd: can't cd to blat

I need to admit that our most wanted target is actually `blat` - may be its license has changed as well but is missing in this archive?
Kind regards, Andreas.

**Comment by maximilianh** [comment]
>
> I did not changed the tarball (yet) since it has no tagged release
>
Sorry can you explain what you mean with "the tarball", and what you mean
with "it"


> and I can override the build process in debian/rules easily
> <https://salsa.debian.org/med-team/kent-core/-/blob/master/debian/rules#L14-L15>.
>
>
Sorry, I don't know what this sentence means. Does this mean that you don't
need a makefile?

> However, even in this case the build process fails
> <https://salsa.debian.org/med-team/kent-core/-/jobs/4130819> with
>
Sorry, can you explain what you mean with "in this case" - which case?

**Comment by maximilianh** [comment]
> I need to admit that our most wanted target is actually blat

BLAT was written by Jim Kent outside of his UCSC job and he holds the
copyright. BLAT is not under an MIT license, so it is not contained in this
repo. I think you have tried before to convince Jim to give BLAT away for
free, and he rejected it. As far as I know, his opinion has not changed.

**Comment by tillea** [comment]
Am Wed, Apr 12, 2023 at 01:28:29PM -0700 schrieb Maximilian Haeussler:
> >
> > I did not changed the tarball (yet) since it has no tagged release
> >
> Sorry can you explain what you mean with "the tarball", and what you mean
> with "it"

For the Debian package I fetch a tarball that is created by Github from
a tag.  If there is a new tag, I fetch a new tarball with the version
determined by the tag.

> > and I can override the build process in debian/rules easily
> > <https://salsa.debian.org/med-team/kent-core/-/blob/master/debian/rules#L14-L15>.
> >
> >
> Sorry, I don't know what this sentence means. Does this mean that you don't
> need a makefile?

A makefile is perfectly welcome since it expresses the explicit way
upstream intends to build the source and gives upstream control over the
build process (which might change from release to release).  In this
specific case where I would have to change a tagged release tarball
which is either by doing not clean or add another patch to the Debian
package which reproduces your commited makefile I decided for the cleaner
approach and added the one liner to the debian/rules file (which is a
makefile as well).
I will remove that one liner from debian/rules once the makefile will
show up inside a tagged release.
 
> > However, even in this case the build process fails
> > <https://salsa.debian.org/med-team/kent-core/-/jobs/4130819> with
> >
> Sorry, can you explain what you mean with "in this case" - which case?

The "case" when I try to build with the very same statement as in your
makefile.  Did you tried make inside the kent-core repository?  You
should be able to reproduce the result in the linked build log.

Kind regards, Andreas.

**Comment by tillea** [comment]
Am Wed, Apr 12, 2023 at 01:31:05PM -0700 schrieb Maximilian Haeussler:
> > I need to admit that our most wanted target is actually blat
> 
> BLAT was written by Jim Kent outside of his UCSC job and he holds the
> copyright. BLAT is not under an MIT license, so it is not contained in this
> repo. I think you have tried before to convince Jim to give BLAT away for
> free, and he rejected it. As far as I know, his opinion has not changed.

What is the most straightforward way to ask Kent again?  (Which e-mail
address, issue tracker, whatever is he reading these days?)

Kind regards, Andreas.

**Comment by maximilianh** [comment]
You can find his email address on his home page:
https://users.soe.ucsc.edu/~kent/

**Comment by maximilianh** [comment]
I did not test "make clean", not sure why that is important when building
on throw-away VMs, but fixed this now. Also added a ton of tools, many
thanks for this comment, it make me realized that the entire src/hg/*
branch was missing. Added now. And tagged as "v447-test". Can you try the
build again?

**Comment by tillea** [comment]
> I did not test "make clean", not sure why that is important when building on throw-away VMs, but fixed this now.

Thanks for fixing this.  To let you understand why `make clean` is important at least for the Debian packaging:  Its simply part of the build process to start in a clean build directory and packagers should make sure that a package builds from scratch twice in a row which presupposes that `make clean` works and leaves the build directory in an identical state as unpacking the source tarball.

>  Also added a ton of tools, many thanks for this comment, it make me realized that the entire src/hg/* branch was missing. Added now. And tagged as "v447-test". Can you try the build again?

I did a test build (without any Debian specific patches).  The build went smoothly until

    make[3]: Leaving directory '/build/kent-core-447-test/src/hg/lib'
    cd hg/cgilib && /usr/bin/make
    /bin/sh: 1: cd: can't cd to hg/cgilib
    make[2]: *** [makefile:33: hgLib] Error 2

Feel free to check [the full build log](https://salsa.debian.org/med-team/kent-core/-/jobs/4133336) in our packaging CI.
Thanks a lot for your cooperation, Andreas.

**Comment by maximilianh** [comment]
Oops, sorry, I pushed this change to the wrong repo first. Should be fixed
now. Tag is v447-test2

**Comment by tillea** [comment]
Thanks again for the quick fix.  Feel free to blame me some pretty different patch in my initial Makefile patch.  I had to fix the libssl linking in [another patch](https://salsa.debian.org/med-team/kent-core/-/blob/master/debian/patches/link_ssl.patch) to enable building in a clean Debian chroot.  I consider your way of linking statically with explicit PATH options for different architectures unusual.  Do you have some specific reason to do so instead of simply using `-lssl`?

The build now ends (again) in

    make[4]: Leaving directory '/build/kent-core-447-test2/src/utils/bedGeneParts'
    make[3]: Leaving directory '/build/kent-core-447-test2/src/utils'
    cd blat && make test
    /bin/sh: 1: cd: can't cd to blat
    make[2]: *** [makefile:131: blat.test] Error 2

and you can inspect the full build log [here](https://salsa.debian.org/med-team/kent-core/-/jobs/4133458).
Thanks again for your quick response, Andreas.

**Comment by maximilianh** [comment]
I can run "make clean" fine in my copy of kent-core.

In your build log,
https://salsa.debian.org/med-team/kent-core/-/jobs/4133458/raw I cannot
find the message "can't cd to blat", did you see this exact message?

**Comment by tillea** [comment]
Am Thu, Apr 13, 2023 at 06:55:41AM -0700 schrieb Maximilian Haeussler:
> I can run "make clean" fine in my copy of kent-core.

It works now since your test release.
 
> In your build log,
> https://salsa.debian.org/med-team/kent-core/-/jobs/4133458/raw I cannot
> find the message "can't cd to blat", did you see this exact message?

About 20 lines before the end of the log.  In the non-raw link line
2686.  I'd be astonished if you run `make` yourself if you would not get
that error yourself.

Kind regards, Andreas.

**Comment by tillea** [comment]
Wait a moment.  After I removed the line from debian/rules fully trusting
your makefile the build went further.  I need to check ...

**Comment by tillea** [comment]
Continuing with new build issues:  First I think that the makefiles seem to implement a mix between building and installing software.  There is the common habit to do some `make install` separately from make.  Remembering that you was wondering about the need of `make clean` when talking about some throw-away VMs it might not relevant for you to split into these steps.  I can surely work around this - just mentioning it for your kind consideration.

I realised this mix of building and installing when I stumbled upon the fact that

    mv cartReset /build/kent-core-447-test2/debian/kent-core-web/usr/lib/cgi-bin/kent-core/cartReset

failed since the target directory did not existed.  While it was [simple enough to solve](https://salsa.debian.org/med-team/kent-core/-/blob/master/debian/rules#L16) for me it might make sense to verify that the target directory exists inside the makefile.

The more honest blocker is now that it seems that not all libraries are build as you can see in [the latest build log](https://salsa.debian.org/med-team/kent-core/-/jobs/4134995):

    cc -O -g -g -O2 -ffile-prefix-map=/builds/med-team/kent-core/debian/output/source_dir=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -std=c99 -Wall -Wall das.o ../../lib/x86_64/jkhgap.a ../../lib/x86_64/jkhgapcgi.a ../../lib/x86_64/jkweb.a  -lpthread -lssl -lcrypto ../../htslib/libhts.a -lpng16 -lm -lz  -lm /usr/lib/x86_64-linux-gnu/libmysqlclient.a -ldl -lstdc++ -lrt 
    /usr/bin/ld: cannot find ../../lib/x86_64/jkhgapcgi.a: No such file or directory
    collect2: error: ld returned 1 exit status
    make[4]: *** [makefile:17: compile] Error 1

I checked which static libraries were actually built:

    /build/kent-core-447-test2 # find . -name "*.a"                                                                                                                           
    ./src/parasol/lib/x86_64/paralib.a
    ./src/lib/x86_64/jkweb.a
    ./src/lib/x86_64/optimalLeaf.a
    ./src/lib/x86_64/jkhgap.a
    ./src/htslib/libhts.a

Do you have any idea why `jkhgapcgi.a` was not build?
Kind regards, Andreas.

**Comment by maximilianh** [comment]
Hi Andreas,

I don't know what your build system is doing, it should only run the
top-level "make", without any options, no cd into "src", just the top-level
makefile. I just did that and it's not trying to build "das".

The top-level makefile has this line:

all: bindir
        cd src && ${MAKE} utils USE_HAL=0 USE_FREETYPE=0 USE_HIC=0
BINDIR=$(CURDIR)/bin

bindir:
        mkdir -p bin

It's only building the "utils". Your error occured in the "das" directory,
"das" is a CGI web program, it will not be useful for Debian users. I can
remove the directory from the repo, but thought that I didn't want to get
into stripping things too much, I just removed the parts with a non-MIT
licence for now and a few directories that are not useful and relatively
big.

I don't know what you mean with the "install" comment, it's not installing,
not if you use my top-level makefile, as you can see, it will mv the
binaries into CURDIR/bin so will not write outside the build tree.

**Comment by tillea** [comment]
> Hi Andreas, I don't know what your build system is doing, it should only run the top-level "make", without any options, no cd into "src", just the top-level makefile.

Argh, I just had some remaining `--sourcedirectory=src` which was used before the top-level makefile existed.  Sorry for the noise!

>  Your error occured in the "das" directory, "das" is a CGI web program, it will not be useful for Debian users. I can remove the directory from the repo, but thought that I didn't want to get into stripping things too much, I just removed the parts with a non-MIT licence for now and a few directories that are not useful and relatively big. I don't know what you mean with the "install" comment, it's not installing, not if you use my top-level makefile, as you can see, it will mv the binaries into CURDIR/bin so will not write outside the build tree.

Thanks for the hint.  It makes perfectly sense to keep all free code in that repository and simply not build the code if it is not interesting.

Thanks again for your cooperation and sorry for the noise I've created with the remaining option.

Kind regards, Andreas.

**Comment by maximilianh** [comment]
Thanks for all your work on this! Do you know what the package will be
called? Are you planning to have the package include all the binaries?

**Comment by tillea** [comment]
Am Fri, Apr 14, 2023 at 05:41:09AM -0700 schrieb Maximilian Haeussler:
> Thanks for all your work on this! Do you know what the package will be
> called?

Not yet.  Any suggestions are welcome.  I guess it makes sense to create
a binary package with executable binaries, a dynamic library as well as
a development package with headers and static libraries (this dynamic
library + development package layout is good packaging style for
libraries).  But I have not yet made up my mind.

> Are you planning to have the package include all the binaries?

I'd be seriously interested in suggestions and will follow your advise.

BTW, once I might have some CI test I will also try to build against the
Debian packaged htslib.  I have some patches to build libucsc with a
more recent version of htslib and I will try to apply these - but first
I will try to get things as close as you provide the code to avoid any
more issues (you have seen that even small things can make some
difference. ;-) )

I'll keep you updated on Monday (over the weekend I'll join some tree
planting initiatives in my area :-P )

Kind regards, Andreas.

**Comment by tillea** [comment]
Another remark:  The repository contains the ELF 32-bit LSB executable `src/hg/fishClones/bander.i386`.  Since the Debian source should not contain such binaries I have to exclude this file from upstream source (which is simple enough).  I'm just wondering whether this is intended or can be generally removed.

**Comment by tillea** [comment]
The file `src/webBlat/webBlat.c` contains

    /* Copyright 2004 Jim Kent.  All rights reserved. */

and thus should not belong to this repository of MIT licensed source code.

**Comment by maximilianh** [comment]
Thanks! That was my mistake. Removed.

**Comment by tillea** [comment]
Thanks again for the quick response.

**Comment by tillea** [comment]
> I'd be seriously interested in suggestions and will follow your advise.

Do you have suggestions for the name of the binary package(s)?

**Comment by maximilianh** [comment]
kent-tools ?
genome-browser-tools ?
browser-tools ?

**Comment by tillea** [comment]
Am Mon, Apr 17, 2023 at 05:39:49AM -0700 schrieb Maximilian Haeussler:
> kent-tools ?
> genome-browser-tools ?
> browser-tools ?

Out of these suggestions I'd prefer genome-browser-tools and will start
with this.  Thanks for your suggestions, Andreas.

**Comment by maximilianh** [comment]
Hi Andreas,

do you know if there is any project that ports Debian packages over to
Redhat? If I get a user on e.g. Centos, is there something I can tell them
how to use this package?

**Comment by tillea** [comment]
Am Tue, Apr 18, 2023 at 04:59:41AM -0700 schrieb Maximilian Haeussler:
> do you know if there is any project that ports Debian packages over to
> Redhat? If I get a user on e.g. Centos, is there something I can tell them
> how to use this package?

I admit I have no idea about any RPM based distro.  I know there are some deb2rpm converters out there but I have no idea about their quality and what is recommendable.  The only thing I know is that rpm2deb does not lead to any satisfying result and if I needed a deb from some rpm I usually inspected the srpm (source package) for some metadata and did the packaging manually using hints from there.
Hope this helps, Andreas.

**Comment by maximilianh** [comment]
OK, that's what I had expected. Thanks!

**Comment by tillea** [comment]
I have another question: Once building with your makefile I get lots of binaries inside the `bin/` directory:

    aNotB                       faOneRecord             raToLines
    addCols                     faPolyASizes            raToTab
    aladdin                     faRandomize             randomLines
    ameme                       faRc                    rmFaDups
    ave                         faRenameRecords         rowsToCols
    aveCols                     faSimplify              scrambleFa
    bamToPsl                    faSize                  sizeof
    barChartMaxLimit            faSomeRecords           spacedToTab
    bedClip                     faSplit                 splitFile
    bedCommonRegions            faToFastq               splitFileByColumn
    bedGeneParts                faToNib                 stToXao
    bedGraphPack                faToTab                 strexCalc
    bedGraphToBigWig            faToTwoBit              stringify
    bedJoinTabOffset            faTrans                 subChar
    bedJoinTabOffset.py         faTrimPolyA             subColumn
    bedPileUps                  faTrimRead              subs
    bedRemoveOverlap            fastqStatsAndSubsample  tabInfo
    bedRestrictToPositions      fastqToFa               tabQuery
    bedToBigBed                 findMotif               tabRepeatedFieldsToArrayField
    bigBedInfo                  fixCr                   tabToHtml
    bigBedNamedItems            gapSplit                tabToTabDir
    bigBedSummary               gffPeek                 tableSum
    bigBedToBed                 git-reports             tagStormArrayToCsv
    bigGuessDb                  gmtime                  tagStormCheck
    bigHeat                     headRest                tagStormDeleteTags
    bigWigAverageOverBed        hitreport               tagStormFromTab
    bigWigCat                   htmlCheck               tagStormHoist
    bigWigCluster               htmlPics                tagStormInfo
    bigWigCorrelate             indexfa                 tagStormJoinTab
    bigWigInfo                  indexgl                 tagStormReformat
    bigWigMerge                 ixIxx                   tagStormRenameTags
    bigWigSummary               ixali                   tagStormRenameVals
    bigWigToBedGraph            ixword1                 tagStormToCsv
    bigWigToWig                 ixword3                 tagStormToHtml
    bottleneck                  jkUniq                  tagStormToJson
    bptForTwoBit                jsonToTagStorm          tagStormToSql
    bptLookupStringToBits64     lineCount               tagStormToTab
    bptMakeStringToBits64       linesToRa               tailLines
    calc                        localtime               tdbRename
    catDir                      makepgo                 tdbSort
    catUncomment                matrixClusterColumns    textHist2
    ccCp                        matrixMarketToTsv       textHistogram
    chopFaLines                 matrixNormalize         tickToDate
    chromToUcsc                 matrixToBarChartBed     toLower
    clusterMatrixToBarChartBed  metaFlatten             toUpper
    colTransform                metaHoist               trackDbIndexBb
    convolve                    metaReformat            trixContextIndex
    countChars                  mktime                  trixMultiSearch
    counter                     newProg                 trixSearch
    cpg_lh                      newPythonProg           twoBitDup
    detab                       nibFrag                 twoBitInfo
    dnadust                     nibSize                 twoBitToFa
    dnsInfo                     nt4Frag                 ucscApiClient
    endsInLf                    paraFetch               udcCleanup
    expMatrixToBarchartBed      paraSync                udcFuse
    faAlign                     primeMate               undupFa
    faCmp                       protDust                upper
    faCount                     pslMap                  vcfFilter
    faFilter                    pslMapPostChain         venn
    faFilterN                   pslPosTarget            verticalSplitSqlTable
    faFlyBaseToUcsc             pslRc                   webSync
    faFrag                      pslRemoveFrameShifts    weedLines
    faGapLocs                   pslScore                wigCorrelate
    faGapSizes                  pslSwap                 wigToBigWig
    faNcbiToUcsc                pslToPslx               wordLine
    faNoise                     pslToXa

I wonder which binaries are really user oriented executable and which ones are some kind of internal helpers.  Could you give any hint whether they might fall into different categories or might it even make sense to put some in a different binary package?  (Please note: I'm personally not a user of these binaries not even a bioinformatician thus I really need your help to make some sensible packaging.)
Note: binary names like for instance `calc` are pretty generic and I can not ship this in /usr/bin/ since it conflicts with another executable from the calc package.
Kind regards, Andreas.

**Comment by tillea** [comment]
Another issue is about testing:  `src/makefile` contains a test target but the root makefile not.  Would you mind providing some sensible test target to enable testing for those targets that will be built by the makefile?
Kind regards, Andreas.

**Comment by maximilianh** [comment]
> I wonder which binaries are really user oriented executable and which ones are some kind of internal helpers. Could you
> give any hint whether they might fall into different categories or might it even make sense to put some in a different
> binary package? (Please note: I'm personally not a user of these binaries not even a bioinformatician thus I really need 
> your help to make some sensible packaging.) Note: binary names like for instance `calc` are pretty generic and I can not > ship this in /usr/bin/ since it conflicts with another executable from the calc package. Kind regards, Andreas.

I agree. Sorry, forgot about the generic tools, you're right. The following tools are probably too generic and can be replaced by somwhat experienced linux users with bash commands (e.g. xargs)

wordLine fixCr calc endsInLf ccCp lineCount newProg dnsInfo gmtime localtime upper toUpper toLower tickToDate subChar sizeof

I'm unsure about "randomLines",  I'd leave it, I think there is a bash construct to replace it, but the tool here is much faster and easier to use.

I'd not split up the tools over multiple packages, that seems more work that it's useful, you could split by filetype (e.g. psl-tools, bed-tools, etc), but several tools can be used with several filetypes, so that would be hard to decide then. 

Testing: I don't think you need to implement testing here. Testing of genomics tools it not as easy as you may think. The tests download big input files from our servers. I don't think it's up to the package maintainers to test the tools, we do that before our release and in our nightly builds.

**Comment by tillea** [comment]
> I agree. Sorry, forgot about the generic tools, you're right. The following tools are probably too generic and can be replaced by somwhat experienced linux users with bash commands (e.g. xargs)
> 
> wordLine fixCr calc endsInLf ccCp lineCount newProg dnsInfo gmtime localtime upper toUpper toLower tickToDate subChar sizeof
> 
> I'm unsure about "randomLines", I'd leave it, I think there is a bash construct to replace it, but the tool here is much faster and easier to use.
> 
> I'd not split up the tools over multiple packages, that seems more work that it's useful, you could split by filetype (e.g. psl-tools, bed-tools, etc), but several tools can be used with several filetypes, so that would be hard to decide then.

There is an option to move all tools to `/usr/lib/genome-browser-tools/bin` and place symlinks from `/usr/bin` to those applications that are relevant to be called by users.
 
> Testing: I don't think you need to implement testing here. Testing of genomics tools it not as easy as you may think. The tests download big input files from our servers. I don't think it's up to the package maintainers to test the tools, we do that before our release and in our nightly builds.

I tend to disagree here.  Testing a package is more than testing your tools upstream.  It might uncover issues in the packaging on the Debian system.  Assume a new gcc version might cause issues, some other tool has a conflicting name, some architecture we support in Debian might create issues.  Packages that are containing tests are somehow "privileged" citizens in the Debian package pool since they migrate faster than others etc.  The  Debian Med team is keen on providing tests for every package for theses reasons.  In the case of kent-core I also want to use the Debian packaged htslib - thus I would be happy to test whether it works as expected.

Kind regards, Andreas.

**Comment by maximilianh** [comment]
I can add a testing target... hopefully it'll just work... but I doubt
that, because it'll want to to test all other non-MIT code.

You cannot use the package Debian htslib. We modified htslib to use our
caching layer.

**Comment by tillea** [comment]
> I can add a testing target... hopefully it'll just work... but I doubt that, because it'll want to to test all other non-MIT code. 

Some defined subset for testing is better than nothing.  There are some packages doing superfluous tests like

    foo --help

which despite its triviality has uncovered issues.  Something that is better than this would be great.

> You cannot use the package Debian htslib. We modified htslib to use our caching layer.

I was afraid you would say so.  I remember the [discussion on our mailing list](https://alioth-lists.debian.net/pipermail/debian-med-packaging/2020-January/077104.html) which somehow should be revived.  In Debian its strongly recommended to avoid code duplication due to security issues and other obstacles.  Thus I'd really recommend to talk do htslib authors how it might be possible to use their official code and whether it is possible to include some enhancements you might depend from.  I'd happily like to initiate some discussion about this if you confirm that this is a sensible goal for your code.

Kind regards, Andreas.

**Comment by maximilianh** [comment]
I am not sure how to implement the tests now. They're testing some of the
non-MIT tools. I'll have to add a lot of exclusions again.

htslib: for this version, you'll have to do with our patched htslib.
Getting the original htslib to add the hooks we need may take some time.
