### ISSUE TITLE
Putting a trimmed down copy of the kent-core source tree in an R package

### ISSUE THREAD

**Issue by hpages** [ucscGenomeBrowser/kent-core#3]
Hi,

I'm working on a new R package that contains a trimmed down copy of the kent-core source tree. The package is intended to support manipulation of `.2bit` files in R. See https://github.com/hpages/Rtwobitlib

First of all, is this acceptable?

If so I'm planning to submit the package to CRAN but I want to make sure that I get the legal stuff right before going any further.

Here's what I've done:

- Copied the `LICENSE` file from https://github.com/ucscGenomeBrowser/kent-core/ to https://github.com/hpages/Rtwobitlib/

- Added a `COPYRIGHTS` file in the package that contains the following lines:
    ```
    YEAR: 2015-2017
    COPYRIGHT HOLDER: UC Regents
    ```

- Listed "UC Regents" as a copyright holder in the `DESCRIPTION` file of the package. See https://github.com/hpages/Rtwobitlib/blob/devel/DESCRIPTION ("UC Regents" is listed with the `"cph"` role in the `Authors@R` field)

Is there anything else I should do?

Thanks for making the code in the kent-core repo open source. There's a lot of very valuable stuff in there!

Best,

Hervé Pagès
Bioconductor Core Team

**Comment by maximilianh** [comment]
Of course - This is exactly why this repo exists ! It’s all under the MIT
license for this reason.

I don’t think there is anything else to do.

You could trim it down, for twoBit reading you only need very little code
but keeping the whole thing may be easier.

**Comment by hpages** [comment]
Perfect, thanks! I already trimmed the code: went from 125096 lines in `kent-core-463/src/lib/` + `kent-core-463/src/inc/` to 10214 lines in `Rtwobitlib/src/kent/` :smiley: Details about the trimming process are in https://github.com/hpages/Rtwobitlib/blob/devel/src/kent/NOTES.txt
